title: "... so lighten up, squirt." # name of the site
author: hava parker # name of site's author
email: hava.xinhua@gmail.com # email of site's author
url: https://auhnix.github.io # root address of the site
description: > # description of the site (multiple lines allowed)
  just me, hello

permalink: /:year/:month/:day/:title:output_ext
tag_page_layout: tag_page
tag_page_dir: tag
paginate: 3
paginate_path: "/blog/:num/"

favicon: "./favicon.gif" # relative path to site's favicon
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%m%d%Y" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate